name: Pass Secrets

on:
  workflow_dispatch:

jobs:
  pass-secrets:
    uses: ./.github/workflows/read-secrets.yml
    secrets:
      MY_CREDENTIAL: ${{ secrets.MY_CREDENTIAL }}
      MY_VAULT_ROLE_ID: ${{ secrets.MY_VAULT_ROLE_ID }}
      MY_VAULT_SECRET_ID: ${{ secrets.MY_VAULT_SECRET_ID }}
